name: coffe_menu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  get_it: ^8.0.2
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16
  flutter_spinkit: ^5.2.1
  elegant_notification: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
    - assets/images/ahamaticLogo.png
    - assets/images/googleLogo.svg
    - assets/images/facebookLogo.svg